#!/usr/bin/php
<?php
include_once __DIR__.'/helpers/console.php';
include_once __DIR__.'/helpers/GitParser.php';
include_once __DIR__.'/helpers/PhpChecker.php';

# Console::log('Im Red!', 'red');
# Console::log('Im Blue on White!', 'white', true, 'blue');

# Console::log('I dont have an EOF', false);
# Console::log("\tThis is where I come in.", 'light_green');
# Console::log('You can swap my variables', 'black', 'yellow');
# Console::log(str_repeat('-', 60));

# echo Console::bell();

// $out = GitParser::getStagedFiles();
$out = GitParser::getDiffLines();
echo "<pre>";
print_r($out);

throw new Exception(sprintf('There are coding standards violations!'));
function extractCommitedFiles()
{
    $output = array();
    $rc = 0;

    exec('git rev-parse --verify HEAD 2> /dev/null', $output, $rc);

    $against = '4b825dc642cb6eb9a060e54bf8d69288fbee4904';
    if ($rc == 0) {
        $against = 'HEAD';
    }

    exec("git diff-index --cached --name-status $against | egrep '^(A|M)' | awk '{print $2;}'", $output);

    return $output;
}