#!/usr/bin/php
<?php
include_once __DIR__.'/helpers/console.php';
include_once __DIR__.'/helpers/GitParser.php';
include_once __DIR__.'/helpers/PhpChecker.php';

$stagedFiles = GitParser::getStagedFiles();
$phpCheck    = PhpChecker::run($stagedFiles);
$hasErrors   = false;
foreach ($phpCheck as $checkName => $errors)
{
	if(is_array($errors) && count($errors))
	{
		$hasErrors = true;
		Console::log("{$checkName}", 'yellow');
		foreach ($errors as $error)
			Console::log("{$error}", 'red');
	}
	else
		Console::log("{$checkName}...ok", 'green');
}

if($hasErrors)
	throw new Exception('ERRORS');